import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/Context/Provider";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html data-theme="dark" lang="en">
        <body className={inter.className}>
        <div className="flex flex-row sm:gap-10">
        <Navbar/>
        <div className="flex w-full flex-col p-4">
          <div className="w-fit">
            <label
              htmlFor="sidebar-mobile-fixed"
              className="btn-primary btn sm:hidden"
            >
              Open Sidebar
            </label>
          </div>

          <div className="my-10">
            {children}
          </div>
        </div>
      </div>
        </body>
      </html>
    </Provider>
  );
}
